In [2]:
import pandas as pd
import numpy as np
import numpy.matlib
import matplotlib.pyplot as plt
dataset = pd.read_csv('suv_data.csv')
dataset.head()
# input
x = dataset.iloc[:,[2,3]].values
# output
y = dataset.iloc[:, 4].values
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test=train_test_split(x,y,test_size=0.10, random_state=0)
print(x_test)


[[    30  87000]
 [    38  50000]
 [    35  75000]
 [    30  79000]
 [    35  50000]
 [    27  20000]
 [    31  15000]
 [    36 144000]
 [    18  68000]
 [    47  43000]
 [    30  49000]
 [    28  55000]
 [    37  55000]
 [    39  77000]
 [    20  86000]
 [    32 117000]
 [    37  77000]
 [    19  85000]
 [    55 130000]
 [    35  22000]
 [    35  47000]
 [    47 144000]
 [    41  51000]
 [    47 105000]
 [    23  28000]
 [    49 141000]
 [    28  87000]
 [    29  80000]
 [    37  62000]
 [    32  86000]
 [    21  88000]
 [    37  79000]
 [    57  60000]
 [    37  53000]
 [    24  58000]
 [    18  52000]
 [    22  81000]
 [    34  43000]
 [    31  34000]
 [    49  36000]]


In [3]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
x_train=sc.fit_transform(x_train)
x_test=sc.transform(x_test)
 
print (x_test[0:10,:])

[[-0.77064501  0.50498616]
 [-0.00663206 -0.57608354]
 [-0.29313691  0.15436896]
 [-0.77064501  0.27124136]
 [-0.29313691 -0.57608354]
 [-1.05714987 -1.45262654]
 [-0.67514339 -1.59871705]
 [-0.19763529  2.17041787]
 [-1.91666444 -0.05015774]
 [ 0.85288251 -0.78061024]]


In [7]:
np.min(x_test[:,1]), np.max(x_test[:, 1])

(-1.598717045429782, 2.1704178713008035)

In [16]:
x_train

array([[-1.05714987,  0.53420426],
       [ 0.2798728 , -0.51764734],
       [-1.05714987,  0.41733186],
       [-0.29313691, -1.45262654],
       [ 0.47087604,  1.23543867],
       [-1.05714987, -0.34233874],
       [-0.10213368,  0.30045946],
       [ 1.33039061,  0.59264046],
       [-1.15265148, -1.16044554],
       [ 1.04388575,  0.47576806],
       [ 1.8078987 ,  1.52761967],
       [-0.38863853, -1.30653604],
       [-0.29313691, -0.37155684],
       [-0.38863853,  1.32309297],
       [ 1.99890194,  0.53420426],
       [ 0.66187928, -1.10200934],
       [-0.86614663,  0.38811376],
       [-1.15265148,  0.30045946],
       [ 1.04388575, -1.21888174],
       [-1.43915634, -1.45262654],
       [-0.57964177, -1.51106275],
       [ 2.09440356, -0.80982834],
       [-1.82116282,  0.18358706],
       [-0.19763529,  0.85560337],
       [-1.82116282, -1.27731794],
       [ 2.09440356,  0.38811376],
       [-1.34365472,  0.56342236],
       [-1.05714987, -0.34233874],
       [ 0.18437118,

In [4]:
from sklearn.linear_model import LogisticRegression
classifier=LogisticRegression(random_state=0)
classifier.fit(x_train,y_train)
y_pred = classifier.predict(x_test)
y_pred
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
 
print ("Confusion Matrix : \n", cm)
from sklearn.metrics import accuracy_score
print ("Accuracy : ", accuracy_score(y_test, y_pred))

Confusion Matrix : 
 [[31  1]
 [ 1  7]]
Accuracy :  0.95
